version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=a
      - MYSQL_DATABASE=chatapp_db
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
      - db_storage:/var/lib/mysql
    command: ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    restart: unless-stopped

  #sonarqube:
  #  image: sonarqube:latest
  #  environment:
  #    - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
  #    - SONARQUBE_JDBC_URL=jdbc:mysql://db:3306/chatapp_db?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance
  #    - SONARQUBE_JDBC_USERNAME=root
  #    - SONARQUBE_JDBC_PASSWORD=a
  #  ports:
  #    - "9000:9000"
  #  volumes:
  #    - sonarqube_data:/opt/sonarqube/data
  #    - sonarqube_extensions:/opt/sonarqube/extensions
  #    - sonarqube_logs:/opt/sonarqube/logs
  #    - sonarqube_temp:/opt/sonarqube/temp
  #  restart: unless-stopped
  #  depends_on:
  #    - db

volumes:
  db_storage:
  #sonarqube_data:
  #sonarqube_extensions:
  #sonarqube_logs:
  #sonarqube_temp:
